# Generated by Django 3.0.3 on 2020-03-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('icon', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('website', models.URLField(blank=True)),
                ('adress', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('activity_area', models.ManyToManyField(to='customer.ActivityArea')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.Country')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.BusinessSize')),
            ],
        ),
    ]
