# Generated by Django 3.0.3 on 2020-03-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssize',
            name='short',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
