# Generated by Django 3.0.3 on 2020-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200301_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssize',
            name='short',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
