# Generated by Django 3.0.3 on 2020-03-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200301_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='activity_area',
            new_name='activity_area_set',
        ),
    ]
