# Generated by Django 3.0.3 on 2020-03-02 01:04

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_country_value_added_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_logo_to),
        ),
    ]
