# Generated by Django 3.0.3 on 2020-03-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200301_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='office',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
    ]
