# Generated by Django 3.0.4 on 2020-03-06 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0010_auto_20200301_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.SET, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
