# Generated by Django 3.0.4 on 2020-03-06 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
