# Generated by Django 3.0.4 on 2020-03-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20200305_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['-date', '-id']},
        ),
    ]
