# Generated by Django 3.0.3 on 2020-03-01 00:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=user.models.UploadTo('photo')),
        ),
    ]
