# Generated by Django 3.0.3 on 2020-03-01 03:25

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_document_documentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to=user.models.upload_document_to),
            preserve_default=False,
        ),
    ]
