# Generated by Django 3.0.3 on 2020-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentname',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
