# Generated by Django 3.0.3 on 2020-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_documentname_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentname',
            name='icon',
            field=models.CharField(default='file', max_length=32),
        ),
    ]
