# Generated by Django 3.0.3 on 2020-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200229_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
