# Generated by Django 3.0.3 on 2020-03-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_biography'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('name', 'user')},
        ),
    ]
